apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: frontend
  namespace: microservices-demo
  annotations:
    fluxcd.io/ignore: "false"
    # fluxcd.io/automated: "true" Аннотация разрешает автоматическое обновление релиза в  Kubernetes кластере
    # в случае изменения версии Docker образа в Registry
    fluxcd.io/automated: "true"
    # Указываем Flux следить за обновлениями конкретных Docker образов
    # в Registry.
    # Новыми считаются только образы, имеющие версию выше текущей и
    # отвечающие маске семантического версионирования ~0.0 (например,
    # 0.0.1, 0.0.72, но не 1.0.0)
    flux.weave.works/tag.chart-image: semver:~v0.0
spec:
  releaseName: frontend
  helmVersion: v3
  # Helm chart, используемый для развертывания релиза. В нашем случае
  #указываем git-репозиторий, и директорию с чартом внутри него
  chart:
    git: git@gitlab.com:dpnev/microservices-demo.git
    ref: main
    path: deploy/charts/frontend
  # Переопределяем переменные Helm chart. В дальнейшем Flux может сам
  # переписывать эти значения и делать commit в git-репозиторий (например,
  # изменять тег Docker образа при его обновлении в Registry)
  values:
    image:
      repository: cr.yandex/crpn6n5ssda7s8tdsdf5/frontend
      tag: v0.0.1