apiVersion: v1
kind: Pod
metadata:
  name: storage-pod
  labels:
    app: storage-pod
spec:
  containers:
    - name: storage-pod
      command:
        - "sleep"
        - "1000000"
      image: busybox
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /data
          name: csi-volume
  volumes:
    - name: csi-volume
      persistentVolumeClaim:
        claimName: storage-pvc
  restartPolicy: Always