---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-iptables-tailer
subjects:
  - kind: ServiceAccount
    name: kube-iptables-tailer
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: kube-iptables-tailer
  apiGroup: rbac.authorization.k8s.io
