apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: http-status
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: nginx-exporter
      port: 9113
      protocol: TCP
      targetPort: 9113