master:
  replicaCount: 3
  nodeSelector: &nodeSelector
    yandex.cloud/node-group-id: cat923baqsdrsiilosoh

  tolerations: &tolerations
    - key: node-role
      operator: Equal
      value: infra
      effect: NoSchedule

data:
  replicaCount: 3
  nodeSelector:
    *nodeSelector
  tolerations:
    *tolerations

coordinating:
  replicaCount: 3
  nodeSelector:
    *nodeSelector
  tolerations:
    *tolerations

ingest:
  replicaCount: 3
  nodeSelector:
    *nodeSelector
  tolerations:
    *tolerations

metrics:
  nodeSelector:
    *nodeSelector
  tolerations:
    *tolerations

#ingress:
#  enabled: true
#  pathType: ImplementationSpecific
#  apiVersion: ""
#  hostname: elasticsearch.local
#  path: /


#  affinity:
#    nodeAffinity:
#      requiredDuringSchedulingIgnoredDuringExecution:
#        nodeSelectorTerms:
#          - matchExpressions:
#              - key: kubernetes.io/os
#                operator: In
#                values:
#                  - linux
