
global:
  imageRegistry: ""
  imagePullSecrets: []
  storageClass: ""
  elasticsearch:
    service:
      name: elasticsearch
      ports:
        restAPI: 9200
  kibanaEnabled: false


kubeVersion: ""
nameOverride: ""
fullnameOverride: ""
commonLabels: {}
commonAnnotations: {}
clusterDomain: cluster.local
extraDeploy: []
namespaceOverride: ""

diagnosticMode:
  enabled: false
  command:
    - sleep
  args:
    - infinity


clusterName: elastic
containerPorts:
  restAPI: 9200
  transport: 9300
plugins: ""
snapshotRepoPath: ""
config: {}
extraConfig: {}
extraHosts: []
extraVolumes: []
extraVolumeMounts: []
initScripts: {}
initScriptsCM: ""
initScriptsSecret: ""
extraEnvVars: []
extraEnvVarsCM: ""
extraEnvVarsSecret: ""
sidecars: []
initContainers: []
useIstioLabels: true

image:
  registry: docker.io
  repository: bitnami/elasticsearch
  tag: 8.6.2-debian-11-r2
  digest: ""
  pullPolicy: IfNotPresent
  pullSecrets: []
  debug: false

security:
  enabled: false
  elasticPassword: ""
  existingSecret: ""
  fipsMode: false
  tls:
    restEncryption: true
    autoGenerated: false
    verificationMode: "full"
    master:
      existingSecret: ""
    data:
      existingSecret: ""
    ingest:
      existingSecret: ""
    coordinating:
      existingSecret: ""
    keystoreFilename: elasticsearch.keystore.jks
    truststoreFilename: elasticsearch.truststore.jks
    usePemCerts: false
    passwordsSecret: ""
    keystorePassword: ""
    truststorePassword: ""
    keyPassword: ""
    secretKeystoreKey: ""
    secretTruststoreKey: ""
    secretKey: ""


service:
  type: ClusterIP
  ports:
    restAPI: 9200
    transport: 9300
  nodePorts:
    restAPI: ""
    transport: ""
  clusterIP: ""
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  externalTrafficPolicy: Cluster
  annotations: {}
  extraPorts: []
  sessionAffinity: None
  sessionAffinityConfig: {}

ingress:
  enabled: false
  pathType: ImplementationSpecific
  apiVersion: ""
  hostname: elasticsearch.local
  path: /
  annotations: {}
  tls: false
  selfSigned: false
  ingressClassName: ""
  extraHosts: []
  extraPaths: []
  extraTls: []
  secrets: []
  extraRules: []


master:
  masterOnly: true
  replicaCount: 2
  nameOverride: ""
  fullnameOverride: ""
  servicenameOverride: ""
  annotations: {}
  updateStrategy:
    type: RollingUpdate
  resources:
    limits: {}
    requests:
      cpu: 25m
      memory: 256Mi
  heapSize: 128m
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    runAsUser: 1001
    runAsNonRoot: true
  hostAliases: []
  podLabels: {}
  podAnnotations: {}
  podAffinityPreset: ""
  podAntiAffinityPreset: ""
  nodeAffinityPreset:
    type: ""
    key: ""
    values: []
  affinity: {}
  nodeSelector: {}
  tolerations: []
  priorityClassName: ""
  schedulerName: ""
  terminationGracePeriodSeconds: ""
  topologySpreadConstraints: []
  podManagementPolicy: "Parallel"
  startupProbe:
    enabled: false
    initialDelaySeconds: 90
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
  livenessProbe:
    enabled: true
    initialDelaySeconds: 90
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
  readinessProbe:
    enabled: true
    initialDelaySeconds: 90
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
  customStartupProbe: {}
  customLivenessProbe: {}
  customReadinessProbe: {}
  command: []
  args: []
  lifecycleHooks: {}
  extraEnvVars: []
  extraEnvVarsCM: ""
  extraEnvVarsSecret: ""
  extraVolumes: []
  extraVolumeMounts: []
  sidecars: []
  initContainers: []
  persistence:
    enabled: true
    storageClass: ""
    existingClaim: ""
    existingVolume: ""
    selector: {}
    annotations: {}
    accessModes:
      - ReadWriteOnce
    size: 8Gi
  serviceAccount:
    create: false
    name: ""
    automountServiceAccountToken: true
    annotations: {}
  autoscaling:
    enabled: false
    minReplicas: 3
    maxReplicas: 11
    targetCPU: ""
    targetMemory: ""


data:
  replicaCount: 2
  nameOverride: ""
  fullnameOverride: ""
  servicenameOverride: ""
  annotations: {}
  updateStrategy:
    type: RollingUpdate
  resources:
    limits: {}
    requests:
      cpu: 25m
      memory: 2048Mi
  heapSize: 1024m
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    runAsUser: 1001
    runAsNonRoot: true
  hostAliases: []
  podLabels: {}
  podAnnotations: {}
  podAffinityPreset: ""
  podAntiAffinityPreset: ""
  nodeAffinityPreset:
    type: ""
    key: ""
    values: []
  affinity: {}
  nodeSelector: {}
  tolerations: []
  priorityClassName: ""
  schedulerName: ""
  terminationGracePeriodSeconds: ""
  topologySpreadConstraints: []
  podManagementPolicy: "Parallel"
  startupProbe:
    enabled: false
    initialDelaySeconds: 90
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
  livenessProbe:
    enabled: true
    initialDelaySeconds: 90
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
  readinessProbe:
    enabled: true
    initialDelaySeconds: 90
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
  customStartupProbe: {}
  customLivenessProbe: {}
  customReadinessProbe: {}
  command: []
  args: []
  lifecycleHooks: {}
  extraEnvVars: []
  extraEnvVarsCM: ""
  extraEnvVarsSecret: ""
  extraVolumes: []
  extraVolumeMounts: []
  sidecars: []
  initContainers: []
  persistence:
    enabled: true
    storageClass: ""
    existingClaim: ""
    existingVolume: ""
    selector: {}
    annotations: {}
    accessModes:
      - ReadWriteOnce
    size: 8Gi
  serviceAccount:
    create: false
    name: ""
    automountServiceAccountToken: true
    annotations: {}
  autoscaling:
    enabled: false
    minReplicas: 3
    maxReplicas: 11
    targetCPU: ""
    targetMemory: ""


coordinating:
  replicaCount: 2
  nameOverride: ""
  fullnameOverride: ""
  servicenameOverride: ""
  annotations: {}
  updateStrategy:
    type: RollingUpdate
  resources:
    limits: {}
    requests:
      cpu: 25m
      memory: 256Mi
  heapSize: 128m
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    runAsUser: 1001
    runAsNonRoot: true
  hostAliases: []
  podLabels: {}
  podAnnotations: {}
  podAffinityPreset: ""
  podAntiAffinityPreset: ""
  nodeAffinityPreset:
    type: ""
    key: ""
    values: []
  affinity: {}
  nodeSelector: {}
  tolerations: []
  priorityClassName: ""
  schedulerName: ""
  terminationGracePeriodSeconds: ""
  topologySpreadConstraints: []
  podManagementPolicy: "Parallel"
  startupProbe:
    enabled: false
    initialDelaySeconds: 90
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
  livenessProbe:
    enabled: true
    initialDelaySeconds: 90
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
  readinessProbe:
    enabled: true
    initialDelaySeconds: 90
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
  customStartupProbe: {}
  customLivenessProbe: {}
  customReadinessProbe: {}
  command: []
  args: []
  lifecycleHooks: {}
  extraEnvVars: []
  extraEnvVarsCM: ""
  extraEnvVarsSecret: ""
  extraVolumes: []
  extraVolumeMounts: []
  sidecars: []
  initContainers: []
  serviceAccount:
    create: false
    name: ""
    automountServiceAccountToken: true
    annotations: {}
  autoscaling:
    enabled: false
    minReplicas: 3
    maxReplicas: 11
    targetCPU: ""
    targetMemory: ""


ingest:
  enabled: true
  replicaCount: 2
  nameOverride: ""
  fullnameOverride: ""
  servicenameOverride: ""
  annotations: {}
  containerPorts:
    restAPI: 9200
    transport: 9300
  updateStrategy:
    type: RollingUpdate
  resources:
    limits: {}
    requests:
      cpu: 25m
      memory: 256Mi
  heapSize: 128m
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    runAsUser: 1001
    runAsNonRoot: true
  hostAliases: []
  podLabels: {}
  podAnnotations: {}
  podAffinityPreset: ""
  podAntiAffinityPreset: ""
  nodeAffinityPreset:
    type: ""
    key: ""
    values: []
  affinity: {}
  nodeSelector: {}
  tolerations: []
  priorityClassName: ""
  schedulerName: ""
  terminationGracePeriodSeconds: ""
  topologySpreadConstraints: []
  podManagementPolicy: "Parallel"
  startupProbe:
    enabled: false
    initialDelaySeconds: 90
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
  livenessProbe:
    enabled: true
    initialDelaySeconds: 90
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
  readinessProbe:
    enabled: true
    initialDelaySeconds: 90
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
  customStartupProbe: {}
  customLivenessProbe: {}
  customReadinessProbe: {}
  command: []
  args: []
  lifecycleHooks: {}
  extraEnvVars: []
  extraEnvVarsCM: ""
  extraEnvVarsSecret: ""
  extraVolumes: []
  extraVolumeMounts: []
  sidecars: []
  initContainers: []
  serviceAccount:
    create: false
    name: ""
    automountServiceAccountToken: true
    annotations: {}
  autoscaling:
    enabled: false
    minReplicas: 3
    maxReplicas: 11
    targetCPU: ""
    targetMemory: ""

  service:
    enabled: false
    type: ClusterIP
    ports:
      restAPI: 9200
      transport: 9300
    nodePorts:
      restAPI: ""
      transport: ""
    clusterIP: ""
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    externalTrafficPolicy: Cluster
    extraPorts: []
    annotations: {}
    sessionAffinity: None
    sessionAffinityConfig: {}
  ingress:
    enabled: false
    pathType: ImplementationSpecific
    apiVersion: ""
    hostname: elasticsearch-ingest.local
    path: /
    annotations: {}
    tls: false
    selfSigned: false
    ingressClassName: ""
    extraHosts: []
    extraPaths: []
    extraTls: []
    secrets: []
    extraRules: []



metrics:
  enabled: false
  nameOverride: ""
  fullnameOverride: ""
  image:
    registry: docker.io
    repository: bitnami/elasticsearch-exporter
    tag: 1.5.0-debian-11-r73
    digest: ""
    pullPolicy: IfNotPresent
    pullSecrets: []
  annotations:
    helm.sh/hook: "post-install,post-upgrade"
    helm.sh/hook-weight: "5"
  extraArgs: []
  hostAliases: []
  schedulerName: ""
  priorityClassName: ""
  service:
    type: ClusterIP
    port: 9114
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9114"
  podAffinityPreset: ""
  podAntiAffinityPreset: ""
  nodeAffinityPreset:
    type: ""
    key: ""
    values: []
  affinity: {}
  nodeSelector: {}
  tolerations: []
  topologySpreadConstraints: []
  resources:
    limits: {}
    requests: {}
  livenessProbe:
    enabled: true
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 5
  startupProbe:
    enabled: false
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 5
  customStartupProbe: {}
  customLivenessProbe: {}
  customReadinessProbe: {}
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9114"
  podLabels: {}
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    runAsUser: 1001
    runAsNonRoot: true
  command: []
  args: []
  extraEnvVars: []
  extraEnvVarsCM: ""
  extraEnvVarsSecret: ""
  extraVolumes: []
  extraVolumeMounts: []
  sidecars: []
  initContainers: []
  serviceMonitor:
    enabled: false
    namespace: ""
    jobLabel: ""
    interval: ""
    scrapeTimeout: ""
    relabelings: []
    metricRelabelings: []
    selector: {}
    labels: {}
    honorLabels: false
  prometheusRule:
    enabled: false
    namespace: ""
    additionalLabels: {}
      # - alert: es cluster error
      #   annotations:
      #     summary: "es cluster error"
      #     description: "es cluster error, cluster state {{`{{`}} $labels.color {{`}}`}}"
      #   expr: elasticsearch_cluster_health_status{color="red"} ==1 or elasticsearch_cluster_health_status{color="yellow"} ==1
      #   for: 1m
      #   labels:
      #     severity: critical
      #     group: PaaS
    rules: []


volumePermissions:
  enabled: false
  image:
    registry: docker.io
    repository: bitnami/bitnami-shell
    tag: 11-debian-11-r87
    digest: ""
    pullPolicy: IfNotPresent
    pullSecrets: []
  resources:
    limits: {}
    requests: {}

sysctlImage:
  enabled: true
  registry: docker.io
  repository: bitnami/bitnami-shell
  tag: 11-debian-11-r87
  digest: ""
  pullPolicy: IfNotPresent
  pullSecrets: []
  resources:
    limits: {}
    requests: {}


kibana:
  elasticsearch:
    hosts:
      - '{{ include "elasticsearch.service.name" . }}'
    port: '{{ include "elasticsearch.service.ports.restAPI" . }}'

